name: Build & Deploy (Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Let Puppeteer download Chromium during npm ci
      - run: echo "PUPPETEER_SKIP_DOWNLOAD=false" >> $GITHUB_ENV

      - run: npm ci

      # If you prefer system Chromium instead, replace the two steps above with Option B.

      - name: Build
        run: node build.mjs
        env:
          NODE_ENV: production
          DEV: "false"
          # Pass through executable path if set by puppeteer install; harmless if empty
          PUPPETEER_EXECUTABLE_PATH: ${{ env.PUPPETEER_EXECUTABLE_PATH }}

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
